language: python
python:
  - "2.7"
install:
  - pip install -e '.[test]'
  - python setup.py develop
  - pip install pytest
  - pip install pytest-django
  - pip install pytest-coverage
  - pip install coveralls
script:
  - py.test --cov baobab
after_success:
  - coveralls
